language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
sudo: false
matrix:
  include:
    - language: python
      python:
        - "3.7"
      dist: xenial
      sudo: true

install: pip install tox-travis

script: tox

notifications:
    email: false
